language: go
go:
- 1.6.x
- 1.7.x
- 1.8.x
install: make deps
script: make
before_deploy: make dist
deploy:
  provider: releases
  api_key:
    secure: JszBI+9B57NsE7v9BUfXaS37gdURL3fhVdbJes1t1O9ZLwnWyL3AJCMzmH+3nsoAbpET6J0s0mgXLqLMooFQ1kJqa0iq9Shxakr5oy1rsX7xHDU6E6qM29MwmxVTFnAclmK0swquKTFgXGQN2+SC/LW5/2T4rJfmgIxX+0iJJz8zy60ODz+gN8OeDgxCeJO2KTU48jgLGz0wPfPa3iS/ygDp2WoThNcSD02mzS6g1F1YqgEVz93advmKAI++iu+xDsXx6nTapRqdtbY9ol0ToKmupDlGH1X8X+eePfGlqzC0EWLnrpATMulu4ShKrsUX5sdVUkzP9/bNxwebu/enBXi1M2Bt6XG9nz3ePjXopMqiWwZGgaCN29v6oGGVZm9bRMea73yWzbV9DY87/zBrEqBei7t4dk74pEpkA9NsoFDpAez0xNsb/tZZ1cRqSatCbch3CoVKIje/deWmImm4EDEPTEi2qTbqzPOFbrRheXTEHUzNh8UZDARKhVBmg/GGSj4i2svDsGlMydtMz41TivRPls9jegvhWXHFc+mFmYJerbGfD27ezbFD+v9OACuw56pyqnjE0wvUse5PuShJ1ZPMNIeTtBKn+ZQtk2MDzjpHT3aJVJWSo0hsyKCIMM1ObxQSZ0a9qQ0yf1gdfvrdEpPghWrU3Z7KwUYgXAAbrlc=
  file_glob: true
  file:
    - dist/*-v*.tar.gz
    - dist/*-v*.zip
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+(\.[0-9]+)?(-[^ \t\r\n\v\f]*)?$ && $TRAVIS_GO_VERSION =~ ^1\.8\.[0-9]+$
